--THIS IS HOW WE WRITE COMMENT IN SQL
--Single line comment look like this
/*
 This is how we write
 multi line comment
 */
--each query we write known as sql SELECT statement
-- * means all COLUMNS
--JUST LIKE JAVA SQL STATEMENT END WITH ;
SELECT * FROM REGIONS;

SELECT * FROM COUNTRIES;

SELECT * FROM LOCATIONS;

SELECT * FROM DEPARTMENTS;

SELECT * FROM JOBS;

SELECT * FROM JOB_HISTORY;

SELECT * FROM EMPLOYEES;

--RESTRICTION COLUMN IN THE RESULT
--sql is space insensitive
SELECT FIRST_NAME
FROM EMPLOYEES;

SELECT FIRST_NAME , LAST_NAME , EMAIL
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT  LOCATION_ID, STREET_ADDRESS, POSTAL_CODE
FROM LOCATIONS;