--THIS IS HOW WE WRITE COMMENT IN SQL
--Single line comment look like this
/*
 This is how we write
 multi line comment
 */
--each query we write known as sql SELECT statement
-- * means all COLUMNS
--JUST LIKE JAVA SQL STATEMENT END WITH ;
SELECT *
FROM REGIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM LOCATIONS;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM JOBS;

SELECT *
FROM JOB_HISTORY;

SELECT *
FROM EMPLOYEES;

--RESTRICTION COLUMN IN THE RESULT
--sql is space insensitive
SELECT FIRST_NAME
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;

SELECT LOCATION_ID, STREET_ADDRESS, POSTAL_CODE
FROM LOCATIONS;

/**
  only getting Unique value from the result
  for example, only get unique 1st name from employee
  table
 */

SELECT DISTINCT FIRST_NAME
FROM EMPLOYEES;

SELECT DISTINCT LAST_NAME
FROM EMPLOYEES;

--THIS IS LOOKING FOR PEOPLE WITH UNIQUE FULL NAME
--THAT MEANS NOT THE SAME AS ANYONE ELSE
SELECT DISTINCT FIRST_NAME, LAST_NAME
FROM EMPLOYEES;

--RESTRICTION ROWS IN THE RESULT USING WHERE CLAUSE

--OPERATORS : = , > >= , < <= , != , <>
--LOGICAL OPERATORS : AND , OR

--DISPLAY The employee information for the employee with first name Ellen
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = 'Ellen';
Ellen != ELLEN as values are case sensitive

--Display the employee FIRST_NAME, LAST_NAME, SALARY
--for the employee with SALARY 11000
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = 11000;

--Display the employee FIRST_NAME, LAST_NAME, SALARY
--for the employee with SALARY 4800 and first name
--is David

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'David'
  AND SALARY = 4800;

-- Display the Employee FIRST_NAME, LAST_NAME,SALARY
-- for the employee with SALARY 4800 OR FIRST_NAME David
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'David'
   OR SALARY = 4800;

--Display the employees that make more than 5000 and less than 12000

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 5000
  AND EMPLOYEES.SALARY < 12000;

--Display the employees that have JOB_ID of
--AD_VP
--AD_ASST
--FI_ACCOUNT
--AC_ACCOUNT
SELECT *
FROM EMPLOYEES
WHERE JOB_ID = 'AD_VP'
   OR JOB_ID = 'AD_ASST'
   OR JOB_ID = 'FI_ACCOUNT'
   OR JOB_ID = 'AC_ACCOUNT';
