-- SUB QUERY : QUERY INSIDE ANOTHER QUERY
SELECT MAX(SALARY)
FROM EMPLOYEES;

-- FIND OUT THE MAX SALARY FROM EMPLOYEE TABLE
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000;

--WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIRST QUERY INTO SECOND QUERY
--NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
--AS A BLOCK OF QUERY THAT GENERATE MAX SALARY ANYTIME
--SO EVEN IF MAX SALARY CHANGE AT SOME POINT WE WOULD GET CORRECT RESULT

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEES);


--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKES THE LEAST SALARY

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKES MORE THAN AVERAGE SALARY
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--DISPLAY ALL EMPLOYEES IF SALARY IS NOT 24000 - AKA SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY <> (SELECT MAX(SALARY) FROM EMPLOYEES);

--3RD MAX SALARY -- ALL SALARIES LESS THAN THE SECOND MAX
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY <> (SELECT MAX(SALARY) FROM EMPLOYEES));

--FIND OUT THE FIRST_NAME OF EMPLOYEES WHO WORKS IN EXECUTIVE DEPARTMENT
-- FIND OUT THE DEPARTMENT ID OF EXECUTIVE
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Executive';

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                         WHERE DEPARTMENT_NAME = 'Executive');



